version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: fintrackr-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: fintrackr_dev
      POSTGRES_USER: fintrackr
      POSTGRES_PASSWORD: fintrackr_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - fintrackr-dev-network


  # FinTrackr Backend API for Development
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fintrackr-api-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://fintrackr:fintrackr_password@postgres:5432/fintrackr_dev?schema=public
      JWT_SECRET: dev-jwt-secret-key
      JWT_REFRESH_SECRET: dev-refresh-secret-key
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - fintrackr-dev-network
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  fintrackr-dev-network:
    driver: bridge
