services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
    - ./backend/src:/app/src
    - ./backend/package.json:/app/package.json
    - ./backend/package-lock.json:/app/package-lock.json
    - ./backend/tsconfig.json:/app/tsconfig.json

    command: npm run dev
