name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # 🚀 Deploy to Staging (develop branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'develop' }}
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to STAGING environment..."
          # Add your staging deployment steps here
          # For example:
          # ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          #   cd /app &&
          #   git pull origin develop &&
          #   docker compose -f docker-compose.staging.yml up -d --build
          # '
  
  # 🚀 Deploy to Production (main branch)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to PRODUCTION environment..."
          # Add your production deployment steps here
          # Example:
          # ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} '
          #   cd /app &&
          #   git pull origin main &&
          #   docker compose -f docker-compose.yml up -d --build
          # '
